name: node js app with postgres database

services:
  backend:
    build: .
    ports:
      - "8000:3000"
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devOpsProject
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  pgdata:


