name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

env:
  APP_DIR: /opt/myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Create Ansible Inventory and Private Key
        run: |
          echo "[target]" > inventory.ini

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "${{ secrets.PROD_HOST }} ansible_user=${{ secrets.PROD_USER }} ansible_ssh_private_key_file=prod_key.pem" >> inventory.ini
            echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > prod_key.pem
            chmod 600 prod_key.pem
            export ANSIBLE_KEY=prod_key.pem
          else
            echo "${{ secrets.DEV_HOST }} ansible_user=${{ secrets.DEV_USER }} ansible_ssh_private_key_file=dev_key.pem" >> inventory.ini
            echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > dev_key.pem
            chmod 600 dev_key.pem
            export ANSIBLE_KEY=dev_key.pem
          fi

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini deploy.yml
